# Generated by Django 4.0 on 2021-12-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myimobApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='LotSize',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Taille du lot'),
        ),
        migrations.AddField(
            model_name='house',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='house',
            name='latitude',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='house',
            name='longitude',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='house',
            name='numeroLot',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro du Lot'),
        ),
    ]
